# -*- coding: utf-8 -*-
"""SPK_Beasiswa_Unggulan.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1L7D2XhqDY9oqttcFkiP4payI4leklU7Q

# SPK Beasiswa Unggulan
Sistem Pendukung Keputusan seleksi penerima Beasiswa Unggulan menggunakan metode TOPSIS + BORDA (GDSS).

**Alur Sistem:**
1. Import Library
2. Baca Data Pendaftar
3. Tahap 1 — Verifikasi Administrasi
4. Tahap 2 — Penilaian Substansi (TOPSIS + BORDA)
5. Tahap 3 — Penetapan Kepala Puslapdik
6. Laporan Akhir & Ekspor ke Drive

## Mount Drive & buat folder
"""

import os
import numpy as np
import pandas as pd
from google.colab import drive

drive.mount('/content/drive')

BASE_DIR  = '/content/drive/MyDrive/FinalProject_SPPK_BeasiswaUnggulan'
ADM_DIR   = f'{BASE_DIR}/administrasi'
NILAI_DIR = f'{BASE_DIR}/penilaian'

for folder in [BASE_DIR, ADM_DIR, NILAI_DIR]:
    os.makedirs(folder, exist_ok=True)
    print(f'✅ Folder siap: {folder}')

"""## Generate data pendaftar"""

np.random.seed(99)
N = 100

nama_depan = [
    'Robby','Budi','Citra','Dian','Eko','Fani','Gilang','Hana','Ivan','Jeni',
    'Kiki','Lina','Mario','Nina','Oscar','Putri','Qori','Raka','Sari','Toni',
    'Umar','Vina','Wahyu','Xena','Yudi','Zahra','Adit','Bella','Candra','Dewi',
    'Elsa','Fajar','Gita','Hendra','Indah','Joko','Kartika','Lukman','Mira','Nanda',
    'Okta','Pandu','Rina','Surya','Tika','Ulfa','Vicky','Wulan','Yoga','Zulfa'
]
nama_belakang = [
    'Savalas','Santoso','Dewi','Rahayu','Nugroho','Kusuma','Arya','Putri','Saputra','Lestari',
    'Wijaya','Sari','Hidayat','Permata','Setiawan','Wibowo','Arifin','Subekti','Hartono','Prabowo',
    'Utama','Anwar','Firmansyah','Amalia','Hakim','Nuraini','Siregar','Kurniawan','Maharani','Susanto'
]

def random_nama():
    return f"{np.random.choice(nama_depan)} {np.random.choice(nama_belakang)}"

jenis_tes_list = ['ITP', 'PTE', 'IBT', 'IELTS']
batas_bahasa   = {'ITP': 550, 'PTE': 58, 'IBT': 80, 'IELTS': 6.5}

"""## Loop generate tiap pendaftar"""

rows = []
for i in range(1, N + 1):
    bid = f'BU-{i:03d}'

    sedang_kuliah = bool(np.random.choice([True, False], p=[0.6, 0.4]))
    batas_usia    = 33 if sedang_kuliah else 32
    if np.random.rand() < 0.15:
        usia = np.random.randint(batas_usia + 1, batas_usia + 5)
    else:
        usia = np.random.randint(21, batas_usia + 1)

    if np.random.rand() < 0.12:
        ipk = round(np.random.uniform(2.50, 2.99), 2)
    else:
        ipk = round(np.random.uniform(3.00, 4.00), 2)

    if np.random.rand() < 0.10:
        skor_ukbi = np.random.randint(500, 578)
    else:
        skor_ukbi = np.random.randint(578, 701)

    jenis_tes = np.random.choice(jenis_tes_list)
    batas_min = batas_bahasa[jenis_tes]
    if np.random.rand() < 0.10:
        if jenis_tes == 'IELTS':
            skor_tes = round(np.random.uniform(4.0, 6.4), 1)
        else:
            skor_tes = np.random.randint(int(batas_min * 0.8), batas_min)
    else:
        if jenis_tes == 'IELTS':
            skor_tes = round(np.random.uniform(6.5, 9.0), 1)
        else:
            skor_tes = np.random.randint(batas_min, int(batas_min * 1.3))

    def doc_status(missing_prob=0.05, invalid_prob=0.03):
        r = np.random.rand()
        if r < missing_prob:
            return None, False
        elif r < missing_prob + invalid_prob:
            return f'file.pdf', False
        else:
            return f'file.pdf', True

    rek_file,  rek_valid  = doc_status(0.05, 0.03)
    loa_file,  loa_valid  = doc_status(0.05, 0.03)
    rs_file,   rs_valid   = doc_status(0.04, 0.03)
    esai_file, esai_valid = doc_status(0.04, 0.03)

    rows.append({
        'id':                    bid,
        'nama':                  random_nama(),
        'usia':                  usia,
        'sedang_kuliah':         sedang_kuliah,
        'ipk':                   ipk,
        'skor_ukbi':             skor_ukbi,
        'jenis_tes_bahasa':      jenis_tes,
        'skor_tes_bahasa':       skor_tes,
        'file_rekomendasi':      rek_file,
        'rekomendasi_valid':     rek_valid,
        'file_loa_surat_aktif':  loa_file,
        'loa_valid':             loa_valid,
        'file_rencana_studi':    rs_file,
        'rencana_studi_valid':   rs_valid,
        'file_esai':             esai_file,
        'esai_valid':            esai_valid,
    })

"""## Simpan data pendaftar ke Drive"""

df_pendaftar = pd.DataFrame(rows)
df_pendaftar.to_csv(f'{BASE_DIR}/data_pendaftar.csv', index=False)
print(f'\n✅ data_pendaftar.csv tersimpan ({len(df_pendaftar)} baris)')
print(df_pendaftar.head(5).to_string())

"""## Definisi kriteria per DM"""

KRITERIA = {
    'DM1_Esai': {
        'label': 'DM1_Esai',
        'kriteria': ['Relevansi_Topik', 'Kedalaman_Analisis',
                     'Kualitas_Penulisan', 'Orisinalitas_Ide']
    },
    'DM2_RencanaStudi': {
        'label': 'DM2_RencanaStudi',
        'kriteria': ['Kejelasan_Tujuan', 'Kelayakan_Timeline',
                     'Relevansi_Bidang', 'Dampak_Rencana']
    },
    'DM3_Wawancara': {
        'label': 'DM3_Wawancara',
        'kriteria': ['Motivasi_Komitmen', 'Kemampuan_Komunikasi',
                     'Pemahaman_Bidang', 'Leadership_Potential']
    }
}

"""## Generate & simpan nilai asesor per kriteria per DM"""

semua_ids = df_pendaftar['id'].tolist()
N_ASESOR  = 10

for dm_key, dm_val in KRITERIA.items():
    dm_dir = f'{NILAI_DIR}/{dm_val["label"]}'
    os.makedirs(dm_dir, exist_ok=True)

    for kriteria_nama in dm_val['kriteria']:
        data_nilai = np.random.uniform(50, 101, (len(semua_ids), N_ASESOR)) #range nilai 0 - 100 (seharusnya, tapi bisa ga ya kalo dibuat minimal asesor tuh ngasih 50?)
        df_nilai = pd.DataFrame(
            data_nilai,
            index=semua_ids,
            columns=[f'Asesor_{j+1}' for j in range(N_ASESOR)]
        )
        df_nilai.index.name = 'id'
        df_nilai = df_nilai.round(2)

        path_file = f'{dm_dir}/{kriteria_nama}.csv'
        df_nilai.to_csv(path_file)

    print(f'✅ {dm_val["label"]}: {len(dm_val["kriteria"])} file kriteria tersimpan → {dm_dir}')

"""## Cek struktur folder hasil"""

print('\n📁 Struktur folder di Google Drive:')
for root, dirs, files in os.walk(BASE_DIR):
    level = root.replace(BASE_DIR, '').count(os.sep)
    indent = '    ' * level
    print(f'{indent}📂 {os.path.basename(root)}/')
    sub_indent = '    ' * (level + 1)
    for f in files:
        size = os.path.getsize(os.path.join(root, f))
        print(f'{sub_indent}📄 {f}  ({size:,} bytes)')

print('\n✅ Semua data dummy siap. Lanjut ke kode SPK utama.')

"""## Google Drive"""

from google.colab import drive

# Mount Google Drive
drive.mount('/content/drive')

"""## Import Library"""

import os
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')
from IPython.display import display, HTML

BASE_DIR  = '/content/drive/MyDrive/FinalProject_SPPK_BeasiswaUnggulan'
NILAI_DIR = f'{BASE_DIR}/penilaian'

def header(text, level=1):
    colors = {1: '#1a3c6e', 2: '#2e6da4', 3: '#4a90d9'}
    sizes  = {1: '22px', 2: '18px', 3: '15px'}
    display(HTML(
        f'<h{level} style="color:{colors[level]};font-size:{sizes[level]};'
        f'border-bottom:2px solid {colors[level]};padding-bottom:4px;margin-top:20px">'
        f'{text}</h{level}>'
    ))

def alert(text, kind='info'):
    cfg = {
        'info':    ('#d1ecf1','#0c5460','ℹ️'),
        'success': ('#d4edda','#155724','✅'),
        'danger':  ('#f8d7da','#721c24','❌'),
        'warning': ('#fff3cd','#856404','⚠️'),
    }
    bg, fg, icon = cfg[kind]
    display(HTML(
        f'<div style="background:{bg};color:{fg};padding:10px 14px;'
        f'border-radius:6px;margin:4px 0"><b>{icon} {text}</b></div>'
    ))

"""## Baca Data Pendaftar dari Google Drive"""

df_pendaftar  = pd.read_csv(f'{BASE_DIR}/data_pendaftar.csv')
pendaftar_raw = df_pendaftar.to_dict('records')
print(f'✅ {len(pendaftar_raw)} data pendaftar berhasil dibaca dari Drive')

"""## Tahap 1: Verifikasi Administrasi"""

BATAS_BAHASA      = {'ITP': 550, 'PTE': 58, 'IBT': 80, 'IELTS': 6.5}
BATAS_IPK         = 3.00
BATAS_UKBI        = 578
BATAS_USIA_UMUM   = 32
BATAS_USIA_KULIAH = 33

def cek_bahasa(jenis, skor):
    if jenis not in BATAS_BAHASA:
        return False, f'Jenis tes tidak dikenal: {jenis}'
    minimal = BATAS_BAHASA[jenis]
    lolos   = skor >= minimal
    return lolos, (f'{jenis} {skor} >= {minimal} OK' if lolos
                   else f'{jenis} {skor} < {minimal} (minimal {minimal})')

def verifikasi_administrasi(kandidat):
    flags = []

    ada_rek = pd.notna(kandidat.get('file_rekomendasi')) and bool(kandidat.get('file_rekomendasi'))
    if not ada_rek:
        flags.append('Surat rekomendasi tidak ada')
    elif not bool(kandidat.get('rekomendasi_valid', False)):
        flags.append('Format surat rekomendasi tidak valid — perlu verifikasi manual')

    usia          = kandidat.get('usia', 99)
    sedang_kuliah = bool(kandidat.get('sedang_kuliah', False))
    batas_usia    = BATAS_USIA_KULIAH if sedang_kuliah else BATAS_USIA_UMUM
    if usia > batas_usia:
        flags.append(f'Usia {usia} tahun melebihi batas {batas_usia} tahun')

    ada_loa = pd.notna(kandidat.get('file_loa_surat_aktif')) and bool(kandidat.get('file_loa_surat_aktif'))
    if not ada_loa:
        flags.append('Surat LoA/Surat Aktif tidak ada')
    elif not bool(kandidat.get('loa_valid', False)):
        flags.append('Surat LoA/Aktif tidak valid — perlu verifikasi manual')

    ipk = float(kandidat.get('ipk', 0))
    if ipk < BATAS_IPK:
        flags.append(f'IPK {ipk} di bawah minimal {BATAS_IPK}')

    ukbi = int(kandidat.get('skor_ukbi', 0))
    if ukbi < BATAS_UKBI:
        flags.append(f'UKBI {ukbi} di bawah minimal Unggul ({BATAS_UKBI})')

    jenis_tes = str(kandidat.get('jenis_tes_bahasa', ''))
    skor_tes  = float(kandidat.get('skor_tes_bahasa', 0))
    bahasa_ok, bahasa_pesan = cek_bahasa(jenis_tes, skor_tes)
    if not bahasa_ok:
        flags.append(f'Bahasa asing: {bahasa_pesan}')

    ada_rs = pd.notna(kandidat.get('file_rencana_studi')) and bool(kandidat.get('file_rencana_studi'))
    if not ada_rs:
        flags.append('File rencana studi tidak ada')
    elif not bool(kandidat.get('rencana_studi_valid', False)):
        flags.append('Format rencana studi tidak sesuai — perlu verifikasi manual')

    ada_esai = pd.notna(kandidat.get('file_esai')) and bool(kandidat.get('file_esai'))
    if not ada_esai:
        flags.append('File esai tidak ada')
    elif not bool(kandidat.get('esai_valid', False)):
        flags.append('Format esai tidak sesuai — perlu verifikasi manual')

    return {
        'id':                      kandidat['id'],
        'nama':                    kandidat['nama'],
        'flags':                   flags,
        'lolos_administrasi':      len(flags) == 0,
        'perlu_verifikasi_manual': len(flags) > 0
    }

header("TAHAP 1 — Verifikasi Administrasi (100 Pendaftar)", level=1)

hasil_admin = []
lolos_admin = []

for p in pendaftar_raw:
    res = verifikasi_administrasi(p)
    hasil_admin.append(res)
    if res['lolos_administrasi']:
        lolos_admin.append(p)

df_admin_summary = pd.DataFrame([{
    'ID':             r['id'],
    'Nama':           r['nama'],
    'Status':         '✅ LOLOS' if r['lolos_administrasi'] else '❌ TIDAK LOLOS',
    'Jumlah Masalah': len(r['flags']),
    'Masalah':        ' | '.join(r['flags']) if r['flags'] else '-'
} for r in hasil_admin])

header("Ringkasan Administrasi", level=2)
display(df_admin_summary)

alert(f'Total Pendaftar: {len(pendaftar_raw)} orang', 'info')
alert(f'Lolos Administrasi: {len(lolos_admin)} orang', 'success')
alert(f'Tidak Lolos: {len(pendaftar_raw) - len(lolos_admin)} orang', 'danger')

"""## Hasil Administrasi"""

fig, axes = plt.subplots(1, 2, figsize=(13, 5))
fig.suptitle('Tahap 1 — Hasil Verifikasi Administrasi (100 Pendaftar)',
             fontsize=14, fontweight='bold')

jml_lolos = len(lolos_admin)
jml_tidak = len(pendaftar_raw) - jml_lolos
axes[0].pie(
    [jml_lolos, jml_tidak],
    labels=[f'Lolos ({jml_lolos})', f'Tidak Lolos ({jml_tidak})'],
    colors=['#2ecc71', '#e74c3c'],
    autopct='%1.0f%%', startangle=90,
    textprops={'fontsize': 12}
)
axes[0].set_title('Distribusi Hasil Administrasi')

kategori_flags = {
    'Rekomendasi': 0, 'Usia': 0, 'LoA/Aktif': 0,
    'IPK': 0, 'UKBI': 0, 'Bahasa Asing': 0,
    'Rencana Studi': 0, 'Esai': 0
}
mapping_flag = {
    'rekomendasi': 'Rekomendasi', 'usia': 'Usia', 'loa': 'LoA/Aktif',
    'ipk': 'IPK', 'ukbi': 'UKBI', 'bahasa': 'Bahasa Asing',
    'rencana studi': 'Rencana Studi', 'esai': 'Esai'
}
for r in hasil_admin:
    for f in r['flags']:
        for kw, kat in mapping_flag.items():
            if kw in f.lower():
                kategori_flags[kat] += 1
                break

cats = list(kategori_flags.keys())
vals = list(kategori_flags.values())
bars = axes[1].barh(cats, vals,
                    color=['#e74c3c' if v > 0 else '#bdc3c7' for v in vals])
axes[1].set_xlabel('Jumlah Pendaftar Bermasalah')
axes[1].set_title('Jenis Masalah Administrasi')
axes[1].set_xlim(0, max(vals) + 3)
for bar, val in zip(bars, vals):
    if val > 0:
        axes[1].text(val + 0.1, bar.get_y() + bar.get_height() / 2,
                     str(val), va='center', fontweight='bold')
plt.tight_layout()
plt.show()

df_admin_summary.to_csv(f'{BASE_DIR}/laporan_administrasi.csv', index=False)
alert('laporan_administrasi.csv tersimpan ke Drive', 'success')

"""## Tahap 2: Definisi Kriteria & Fungsi TOPSIS"""

header("TAHAP 2 — Penilaian Substansi (DSS + GDSS)", level=1)

KRITERIA = {
    'DM1_Esai': {
        'label' : 'DM 1 — Esai',
        'folder': 'DM1_Esai',
        'kriteria': [
            {'nama': 'Relevansi_Topik',       'bobot': 0.25, 'tipe': 'benefit'},
            {'nama': 'Kedalaman_Analisis',     'bobot': 0.30, 'tipe': 'benefit'},
            {'nama': 'Kualitas_Penulisan',     'bobot': 0.25, 'tipe': 'benefit'},
            {'nama': 'Orisinalitas_Ide',       'bobot': 0.20, 'tipe': 'benefit'},
        ]
    },
    'DM2_RencanaStudi': {
        'label' : 'DM 2 — Rencana Studi',
        'folder': 'DM2_RencanaStudi',
        'kriteria': [
            {'nama': 'Kejelasan_Tujuan',       'bobot': 0.30, 'tipe': 'benefit'},
            {'nama': 'Kelayakan_Timeline',     'bobot': 0.25, 'tipe': 'benefit'},
            {'nama': 'Relevansi_Bidang',       'bobot': 0.25, 'tipe': 'benefit'},
            {'nama': 'Dampak_Rencana',         'bobot': 0.20, 'tipe': 'benefit'},
        ]
    },
    'DM3_Wawancara': {
        'label' : 'DM 3 — Wawancara',
        'folder': 'DM3_Wawancara',
        'kriteria': [
            {'nama': 'Motivasi_Komitmen',      'bobot': 0.30, 'tipe': 'benefit'},
            {'nama': 'Kemampuan_Komunikasi',   'bobot': 0.25, 'tipe': 'benefit'},
            {'nama': 'Pemahaman_Bidang',       'bobot': 0.25, 'tipe': 'benefit'},
            {'nama': 'Leadership_Potential',   'bobot': 0.20, 'tipe': 'benefit'},
        ]
    }
}

ids_lolos = [p['id']   for p in lolos_admin]
nama_map  = {p['id']: p['nama'] for p in pendaftar_raw}

def baca_matriks_dm(dm_val, kandidat_ids):
    dm_dir  = f'{NILAI_DIR}/{dm_val["folder"]}'
    df_rata = pd.DataFrame(index=kandidat_ids)
    for k in dm_val['kriteria']:
        path      = f'{dm_dir}/{k["nama"]}.csv'
        df_asesor = pd.read_csv(path, index_col='id')
        df_asesor = df_asesor.loc[df_asesor.index.isin(kandidat_ids)]
        df_rata[k['nama']] = df_asesor.mean(axis=1)
    return df_rata

def topsis(matriks, kriteria_list):
    X    = matriks.values.astype(float)
    n, m = X.shape

    norm      = np.sqrt((X ** 2).sum(axis=0))
    norm[norm == 0] = 1e-10
    R = X / norm

    bobot = np.array([k['bobot'] for k in kriteria_list])
    V     = R * bobot

    A_plus  = np.array([V[:, j].max() if kriteria_list[j]['tipe'] == 'benefit'
                        else V[:, j].min() for j in range(m)])
    A_minus = np.array([V[:, j].min() if kriteria_list[j]['tipe'] == 'benefit'
                        else V[:, j].max() for j in range(m)])

    D_plus  = np.sqrt(((V - A_plus)  ** 2).sum(axis=1))
    D_minus = np.sqrt(((V - A_minus) ** 2).sum(axis=1))

    denom       = D_plus + D_minus
    denom[denom == 0] = 1e-10
    Ci = D_minus / denom

    return pd.Series(Ci, index=matriks.index, name='Skor_TOPSIS')

def borda_count(ranking_dict, kandidat_ids):
    n      = len(kandidat_ids)
    scores = pd.Series(0.0, index=kandidat_ids)
    for dm_key, ranking in ranking_dict.items():
        for kid in kandidat_ids:
            scores[kid] += (n - ranking[kid])
    return scores

"""## Baca Matriks Nilai per DM"""

matriks_dm = {}
for dm_key, dm_val in KRITERIA.items():
    matriks_dm[dm_key] = baca_matriks_dm(dm_val, ids_lolos)
    print(f'✅ Matriks {dm_val["label"]} dibaca: {matriks_dm[dm_key].shape}')

header("Contoh Matriks DM1 — Esai (5 kandidat pertama)", level=3)
display(matriks_dm['DM1_Esai'].head().round(3))

"""## TOPSIS per DM"""

skor_topsis    = {}
ranking_topsis = {}

header("Hasil TOPSIS per DM (Top 10)", level=2)
for dm_key, dm_val in KRITERIA.items():
    skor = topsis(matriks_dm[dm_key], dm_val['kriteria'])
    rank = skor.rank(ascending=False, method='min').astype(int)
    skor_topsis[dm_key]    = skor
    ranking_topsis[dm_key] = rank

    df_show = pd.DataFrame({
        'Nama':        [nama_map[i] for i in skor.index],
        'Skor TOPSIS': skor.round(4),
        'Ranking':     rank
    }).sort_values('Ranking').head(10)
    df_show.index = range(1, len(df_show) + 1)

    header(f'{dm_val["label"]} — Top 10', level=3)
    display(df_show)

"""## Agregasi BORDA & Ranking Final"""

borda_scores  = borda_count(ranking_topsis, ids_lolos)
ranking_final = borda_scores.rank(ascending=False, method='min').astype(int)

df_final = pd.DataFrame({'Nama': [nama_map[i] for i in borda_scores.index]})
for dm_key, dm_val in KRITERIA.items():
    label_k = 'Rank ' + dm_val['label'].split('—')[1].strip()
    df_final[label_k] = [ranking_topsis[dm_key][kid] for kid in borda_scores.index]
df_final['Total Poin Borda'] = borda_scores.values.astype(int)
df_final['Ranking Final']    = ranking_final.values
df_final = df_final.sort_values('Ranking Final')
df_final.index = range(1, len(df_final) + 1)

header("Ranking Final — BORDA (Top 20)", level=2)
display(df_final.head(20))

"""## Visualisasi TOPSIS & BORDA"""

fig, axes = plt.subplots(1, 3, figsize=(18, 6))
fig.suptitle('Skor TOPSIS per DM — Top 15 Kandidat', fontsize=14, fontweight='bold')

for idx, (dm_key, dm_val) in enumerate(KRITERIA.items()):
    skor       = skor_topsis[dm_key]
    top15_ids  = skor.sort_values(ascending=False).head(15).index
    top15_nama = [nama_map[i][:15] for i in top15_ids]
    top15_vals = skor[top15_ids].values
    palette    = sns.color_palette('Blues_d', 15)
    bars = axes[idx].barh(top15_nama[::-1], top15_vals[::-1], color=palette)
    axes[idx].set_title(dm_val['label'], fontsize=11)
    axes[idx].set_xlabel('Skor TOPSIS')
    axes[idx].set_xlim(0, 1.05)
    for bar, val in zip(bars, top15_vals[::-1]):
        axes[idx].text(val + 0.005, bar.get_y() + bar.get_height() / 2,
                       f'{val:.3f}', va='center', fontsize=8)
plt.tight_layout()
plt.show()

fig2, ax2 = plt.subplots(figsize=(10, 7))
top20_ids  = borda_scores.sort_values(ascending=False).head(20).index
top20_nama = [nama_map[i][:20] for i in top20_ids]
top20_vals = borda_scores[top20_ids].values
gold = ['#f1c40f','#bdc3c7','#cd6133'] + ['#5dade2'] * 17

bars2 = ax2.barh(top20_nama[::-1], top20_vals[::-1], color=gold[::-1])
ax2.set_title('Top 20 Ranking Final — Metode BORDA', fontsize=13, fontweight='bold')
ax2.set_xlabel('Total Poin Borda')
for bar, val in zip(bars2, top20_vals[::-1]):
    ax2.text(val + 0.1, bar.get_y() + bar.get_height() / 2,
             str(int(val)), va='center', fontsize=9, fontweight='bold')
plt.tight_layout()
plt.show()

"""## Tahap 3: Penetapan Kepala Puslapdik"""

KUOTA_BEASISWA = 10

header("TAHAP 3 — Penetapan Kepala Puslapdik", level=1)
alert(f'Total Pendaftar: {len(pendaftar_raw)} orang', 'info')
alert(f'Lolos Administrasi: {len(lolos_admin)} orang', 'info')
alert(f'Kuota Beasiswa: {KUOTA_BEASISWA} orang', 'info')

df_penetapan = df_final[df_final['Ranking Final'] <= KUOTA_BEASISWA].copy()
df_penetapan['Status Penetapan'] = 'DITETAPKAN'
df_penetapan['Catatan Kepala']   = 'Setuju – sesuai ranking GDSS'

OVERRIDE_RANKING = [3, 7]
ALASAN_OVERRIDE  = {
    3: 'Conflict of interest – tidak dapat ditetapkan',
    7: 'Dokumen pendukung tambahan diperlukan – ditunda',
}

for rank_val, alasan in ALASAN_OVERRIDE.items():
    mask = df_penetapan['Ranking Final'] == rank_val
    df_penetapan.loc[mask, 'Status Penetapan'] = 'OVERRIDE – DITOLAK'
    df_penetapan.loc[mask, 'Catatan Kepala']   = f'Tidak Setuju – {alasan}'

n_override   = len(OVERRIDE_RANKING)
df_pengganti = df_final[df_final['Ranking Final'] > KUOTA_BEASISWA].head(n_override).copy()
df_pengganti['Status Penetapan'] = 'DITETAPKAN (Pengganti)'
df_pengganti['Catatan Kepala']   = 'Masuk sebagai pengganti dari kandidat yang di-override'

df_keputusan = pd.concat([df_penetapan, df_pengganti], ignore_index=True)
df_keputusan = df_keputusan.sort_values(['Status Penetapan', 'Ranking Final'])
df_keputusan.index = range(1, len(df_keputusan) + 1)

ditetapkan = df_keputusan[df_keputusan['Status Penetapan'].str.startswith('DITETAPKAN')]
overridden  = df_keputusan[df_keputusan['Status Penetapan'] == 'OVERRIDE – DITOLAK']

header(f'Penerima Beasiswa Ditetapkan ({len(ditetapkan)} orang)', level=2)
display(ditetapkan)

header(f'Kandidat Di-override oleh Kepala Puslapdik ({len(overridden)} orang)', level=2)
display(overridden)

fig3, axes3 = plt.subplots(1, 2, figsize=(14, 5))
fig3.suptitle('Tahap 3 — Rekapitulasi Penetapan Kepala Puslapdik',
              fontsize=14, fontweight='bold')

status_counts = df_keputusan['Status Penetapan'].value_counts()
colors_status = {
    'DITETAPKAN':             '#2ecc71',
    'DITETAPKAN (Pengganti)': '#5dade2',
    'OVERRIDE – DITOLAK':     '#e74c3c',
}
pie_colors = [colors_status.get(s, '#bdc3c7') for s in status_counts.index]
axes3[0].pie(
    status_counts,
    labels=status_counts.index,
    autopct='%1.0f%%',
    colors=pie_colors,
    startangle=90,
    textprops={'fontsize': 10}
)
axes3[0].set_title('Komposisi Keputusan Penetapan')

top15_nama_keputusan = df_final.head(15)['Nama'].str[:20].values
heatmap_data = pd.DataFrame(
    {dm_val['label'].split('—')[1].strip(): skor_topsis[dm_key].reindex(df_final.head(15).index)
     for dm_key, dm_val in KRITERIA.items()},
    index=top15_nama_keputusan
)
sns.heatmap(
    heatmap_data, annot=True, fmt='.3f', cmap='YlGn',
    ax=axes3[1], linewidths=0.5, cbar_kws={'shrink': 0.8}
)
axes3[1].set_title('Heatmap Skor TOPSIS Top 15 Penerima')
axes3[1].set_ylabel('')

plt.tight_layout()
plt.show()

"""## Laporan Akhir & Ekspor ke Google Drive"""

header("LAPORAN AKHIR — SPK BEASISWA UNGGULAN", level=1)
alert(f'Total Pendaftar: {len(pendaftar_raw)} orang', 'info')
alert(f'Lolos Administrasi: {len(lolos_admin)} orang', 'info')
alert(f'Masuk Tahap Substansi: {len(ids_lolos)} orang', 'info')
alert(f'Kuota Beasiswa: {KUOTA_BEASISWA} orang', 'info')
alert(f'Ditetapkan oleh Kepala Puslapdik: {len(ditetapkan)} orang', 'success')
alert(f'Di-override: {len(overridden)} orang', 'warning')

df_keputusan.to_csv(f'{BASE_DIR}/laporan_penetapan_final.csv', index=False)

df_topsis = pd.DataFrame({
    dm_val['label']: skor_topsis[dm_key]
    for dm_key, dm_val in KRITERIA.items()
})
df_topsis.insert(0, 'Nama', [nama_map[i] for i in df_topsis.index])
df_topsis.to_csv(f'{BASE_DIR}/skor_topsis_per_dm.csv')

df_substansi_final = df_topsis.copy()
for dm_key, dm_val in KRITERIA.items():
    label_rank = 'Rank ' + dm_val['label'].split('—')[1].strip()
    df_substansi_final[label_rank] = ranking_topsis[dm_key].reindex(df_topsis.index).values
df_substansi_final['Total Poin Borda'] = borda_scores.reindex(df_topsis.index).values.astype(int)
df_substansi_final['Ranking Final']    = ranking_final.reindex(df_topsis.index).values
df_substansi_final = df_substansi_final.sort_values('Ranking Final')
df_substansi_final.to_csv(f'{BASE_DIR}/laporan_substansi_final.csv')

rows_substansi = []
for kid in ids_lolos:
    row = {'ID': kid, 'Nama': nama_map[kid]}
    for dm_key, dm_val in KRITERIA.items():
        for k in dm_val['kriteria']:
            row[f'[{dm_val["label"].split("—")[1].strip()}] {k["nama"]}'] = round(matriks_dm[dm_key].loc[kid, k['nama']], 4)
    for dm_key, dm_val in KRITERIA.items():
        row[f'Skor TOPSIS {dm_val["label"].split("—")[1].strip()}'] = round(float(skor_topsis[dm_key][kid]), 4)
    for dm_key, dm_val in KRITERIA.items():
        row[f'Rank {dm_val["label"].split("—")[1].strip()}'] = int(ranking_topsis[dm_key][kid])
    row['Total Poin Borda'] = int(borda_scores[kid])
    row['Ranking Final']    = int(ranking_final[kid])
    rows_substansi.append(row)

df_agregasi_substansi = pd.DataFrame(rows_substansi).sort_values('Ranking Final')
df_agregasi_substansi.index = range(1, len(df_agregasi_substansi) + 1)
df_agregasi_substansi.to_csv(f'{BASE_DIR}/laporan_agregasi_substansi_lengkap.csv', index=False)

alert('Semua laporan tersimpan ke Google Drive:', 'success')
alert(f'{BASE_DIR}/laporan_administrasi.csv', 'info')
alert(f'{BASE_DIR}/laporan_substansi_final.csv', 'info')
alert(f'{BASE_DIR}/skor_topsis_per_dm.csv', 'info')
alert(f'{BASE_DIR}/laporan_penetapan_final.csv', 'info')
alert(f'{BASE_DIR}/laporan_agregasi_substansi_lengkap.csv', 'info')
print("\n✅ Selesai.")