# -*- coding: utf-8 -*-
"""SPPK GDSS Beasiswa BU.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gDvKSNKfKLIO_WC9Jd86oL9mXiTUVwBl
"""

# ============================================================
# SISTEM PENDUKUNG KEPUTUSAN BEASISWA UNGGULAN (BU)
# dengan GDSS (Group Decision Support System)
# Metode: TOPSIS (Individual) + BORDA (GDSS)
# ============================================================
# Cara pakai di Google Colab:
#   1. Copy seluruh kode ini ke satu cell di Google Colab
#   2. Jalankan dengan Shift+Enter
# ============================================================

# ─── INSTALL & IMPORT ───────────────────────────────────────
import subprocess, sys

def install(pkg):
    subprocess.check_call([sys.executable, "-m", "pip", "install", pkg, "-q"])

for pkg in ["pandas", "numpy", "matplotlib", "seaborn", "tabulate", "ipywidgets"]:
    install(pkg)

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.patches as mpatches
import seaborn as sns
from tabulate import tabulate
from IPython.display import display, HTML, clear_output
import warnings
warnings.filterwarnings("ignore")

print("=" * 65)
print("  SISTEM PENDUKUNG KEPUTUSAN BEASISWA UNGGULAN (BU)")
print("  Metode: TOPSIS + GDSS (Borda)")
print("=" * 65)

# ─── BAGIAN 1: GENERATE DATA DUMMY ──────────────────────────
np.random.seed(42)
N = 200

def rand_ukbi():
    # UKBI: Unggul = 578–640, Sangat Unggul = 641–725, Istimewa > 725
    # Ada yang tidak lolos (< 578)
    pool = (
        list(np.random.randint(500, 578, 40)) +   # tidak lolos
        list(np.random.randint(578, 641, 100)) +  # unggul
        list(np.random.randint(641, 726, 45)) +   # sangat unggul
        list(np.random.randint(726, 800, 15))     # istimewa
    )
    np.random.shuffle(pool)
    return pool[:N]

def rand_english():
    """Skor bahasa Inggris: ITP/PTE/IBT/IELTS dikonversi ke skor 0–120."""
    pool = (
        list(np.random.randint(40, 58, 40)) +    # tidak lolos
        list(np.random.randint(58, 80, 80)) +    # PTE lolos
        list(np.random.randint(80, 100, 60)) +   # IBT lolos
        list(np.random.randint(100, 120, 20))    # sangat tinggi
    )
    np.random.shuffle(pool)
    return pool[:N]

names = [f"Pendaftar_{i+1:03d}" for i in range(N)]

data_admin = {
    "ID"               : [f"BU-2025-{i+1:04d}" for i in range(N)],
    "Nama"             : names,
    "Usia"             : np.random.randint(22, 36, N),
    "Status_Kuliah"    : np.random.choice(["Aktif", "Tidak_Aktif"], N, p=[0.90, 0.10]),
    "IPK"              : np.round(np.random.uniform(2.70, 4.00, N), 2),
    "UKBI"             : rand_ukbi(),
    "Skor_Bahasa_Ing"  : rand_english(),
    "Ada_Rekomendasi"  : np.random.choice([True, False], N, p=[0.88, 0.12]),
    "File_Rek_Valid"   : np.random.choice([True, False], N, p=[0.92, 0.08]),
    "Ada_LoA_Aktif"    : np.random.choice([True, False], N, p=[0.85, 0.15]),
    "Ada_Rencana_Studi": np.random.choice([True, False], N, p=[0.90, 0.10]),
    "File_RS_Valid"    : np.random.choice([True, False], N, p=[0.93, 0.07]),
    "Ada_Esai"         : np.random.choice([True, False], N, p=[0.91, 0.09]),
    "File_Esai_Valid"  : np.random.choice([True, False], N, p=[0.94, 0.06]),
}

df_raw = pd.DataFrame(data_admin)
print(f"\n✅ Data dummy berhasil dibuat: {N} pendaftar\n")

# ─── BAGIAN 2: TAHAP ADMINISTRASI ───────────────────────────
print("=" * 65)
print("  TAHAP 1: VERIFIKASI ADMINISTRASI")
print("=" * 65)

def cek_administrasi(row):
    issues = []
    flags  = {}

    # 1. Usia
    usia_ok = (row["Usia"] < 32) or (row["Usia"] <= 33 and row["Status_Kuliah"] == "Aktif")
    flags["Usia_OK"] = usia_ok
    if not usia_ok:
        issues.append("⛔ Usia tidak memenuhi syarat")

    # 2. Rekomendasi
    rek_ok = row["Ada_Rekomendasi"] and row["File_Rek_Valid"]
    flags["Rekomendasi_OK"] = rek_ok
    if not row["Ada_Rekomendasi"]:
        issues.append("⛔ Surat rekomendasi tidak ada")
    elif not row["File_Rek_Valid"]:
        issues.append("🔴 File rekomendasi perlu verifikasi manual")

    # 3. LoA / Surat Aktif
    loa_ok = row["Ada_LoA_Aktif"]
    flags["LoA_OK"] = loa_ok
    if not loa_ok:
        issues.append("⛔ Surat LoA/Surat Aktif tidak ada")

    # 4. IPK
    ipk_ok = row["IPK"] >= 3.00
    flags["IPK_OK"] = ipk_ok
    if not ipk_ok:
        issues.append(f"⛔ IPK {row['IPK']} < 3.00")

    # 5. UKBI
    ukbi_ok = row["UKBI"] >= 578
    flags["UKBI_OK"] = ukbi_ok
    if not ukbi_ok:
        issues.append(f"⛔ UKBI {row['UKBI']} < 578 (min: Unggul)")

    # 6. Bahasa Inggris (skor PTE >= 58 sebagai patokan umum)
    eng_ok = row["Skor_Bahasa_Ing"] >= 58
    flags["BahasaIng_OK"] = eng_ok
    if not eng_ok:
        issues.append(f"⛔ Skor Bahasa Inggris {row['Skor_Bahasa_Ing']} tidak memenuhi syarat")

    # 7. Rencana Studi
    rs_ok = row["Ada_Rencana_Studi"] and row["File_RS_Valid"]
    flags["RencanaStudi_OK"] = rs_ok
    if not row["Ada_Rencana_Studi"]:
        issues.append("⛔ Rencana studi tidak ada")
    elif not row["File_RS_Valid"]:
        issues.append("🔴 File rencana studi perlu verifikasi manual")

    # 8. Esai
    esai_ok = row["Ada_Esai"] and row["File_Esai_Valid"]
    flags["Esai_OK"] = esai_ok
    if not row["Ada_Esai"]:
        issues.append("⛔ Esai tidak ada")
    elif not row["File_Esai_Valid"]:
        issues.append("🔴 File esai perlu verifikasi manual")

    all_ok        = all(flags.values())
    butuh_manusia = any("🔴" in i for i in issues)
    status        = "LULUS" if all_ok else ("VERIFIKASI_MANUAL" if butuh_manusia else "GUGUR")

    return pd.Series({
        **flags,
        "Isu"            : "; ".join(issues) if issues else "✅ Semua persyaratan terpenuhi",
        "Butuh_Manual"   : butuh_manusia,
        "Status_Admin"   : status,
    })

result_admin = df_raw.apply(cek_administrasi, axis=1)
df_admin     = pd.concat([df_raw, result_admin], axis=1)

lulus_admin     = df_admin[df_admin["Status_Admin"] == "LULUS"]
gugur_admin     = df_admin[df_admin["Status_Admin"] == "GUGUR"]
manual_admin    = df_admin[df_admin["Status_Admin"] == "VERIFIKASI_MANUAL"]

print(f"\n📊 REKAPITULASI ADMINISTRASI:")
print(f"   Total pendaftar          : {N}")
print(f"   ✅ Lulus administrasi    : {len(lulus_admin)}")
print(f"   🔴 Perlu verifikasi manual: {len(manual_admin)}")
print(f"   ⛔ Gugur otomatis        : {len(gugur_admin)}")

# Tampilkan contoh yang perlu verifikasi manual
if len(manual_admin) > 0:
    print(f"\n{'='*65}")
    print("  🔴 DAFTAR YANG PERLU VERIFIKASI MANUAL (5 contoh pertama):")
    print(f"{'='*65}")
    cols_show = ["ID", "Nama", "Isu"]
    print(tabulate(manual_admin[cols_show].head(5), headers="keys",
                   tablefmt="grid", showindex=False))

# Tampilkan contoh yang gugur
if len(gugur_admin) > 0:
    print(f"\n{'='*65}")
    print("  ⛔ DAFTAR GUGUR OTOMATIS (5 contoh pertama):")
    print(f"{'='*65}")
    cols_show = ["ID", "Nama", "Isu"]
    print(tabulate(gugur_admin[cols_show].head(5), headers="keys",
                   tablefmt="grid", showindex=False))

# Simulasi: verifikasi manual → sebagian lolos, sebagian gugur
np.random.seed(10)
df_admin.loc[df_admin["Status_Admin"] == "VERIFIKASI_MANUAL", "Status_Admin"] = \
    np.random.choice(["LULUS", "GUGUR"], size=len(manual_admin), p=[0.6, 0.4])

df_lulus_admin = df_admin[df_admin["Status_Admin"] == "LULUS"].copy()
print(f"\n✅ Setelah verifikasi manual → lanjut ke Tahap Substansi: {len(df_lulus_admin)} pendaftar")

# ─── VISUALISASI ADMINISTRASI ───────────────────────────────
fig, axes = plt.subplots(1, 2, figsize=(14, 5))
fig.suptitle("TAHAP ADMINISTRASI – Rekapitulasi", fontsize=14, fontweight="bold")

status_count = df_admin["Status_Admin"].value_counts()
colors_pie = ["#2ecc71", "#e74c3c", "#f39c12"]
axes[0].pie(status_count, labels=status_count.index, autopct="%1.1f%%",
            colors=colors_pie[:len(status_count)], startangle=90)
axes[0].set_title("Status Akhir Administrasi")

kriteria_flags = ["Usia_OK", "Rekomendasi_OK", "LoA_OK", "IPK_OK",
                  "UKBI_OK", "BahasaIng_OK", "RencanaStudi_OK", "Esai_OK"]
pass_rate = df_admin[kriteria_flags].mean() * 100
pass_rate.index = ["Usia", "Rekomendasi", "LoA/Aktif", "IPK",
                   "UKBI", "Bhs Inggris", "Rencana Studi", "Esai"]
bar_colors = ["#2ecc71" if v >= 80 else "#e74c3c" for v in pass_rate]
axes[1].barh(pass_rate.index, pass_rate, color=bar_colors)
axes[1].set_xlabel("% Pendaftar Lolos")
axes[1].set_title("Tingkat Kelulusan per Kriteria Administrasi")
axes[1].set_xlim(0, 110)
for i, v in enumerate(pass_rate):
    axes[1].text(v + 1, i, f"{v:.1f}%", va="center")

plt.tight_layout()
plt.savefig("administrasi_summary.png", dpi=120, bbox_inches="tight")
plt.show()
print("📈 Grafik administrasi tersimpan: administrasi_summary.png")

# ─── BAGIAN 3: TAHAP SUBSTANSI ──────────────────────────────
print("\n" + "=" * 65)
print("  TAHAP 2: SUBSTANSI – TOPSIS + GDSS (BORDA)")
print("=" * 65)

n_sub = len(df_lulus_admin)
ids   = df_lulus_admin["ID"].values
names_sub = df_lulus_admin["Nama"].values

# Generate skor dari 3 DM (skala 1–10)
# DM1: Penilai Esai      → C3 (4 sub-kriteria)
# DM2: Penilai Rencana Studi → C6 (3 sub-kriteria)
# DM3: Penilai Wawancara → C7 (5 sub-kriteria)

np.random.seed(77)

# Skor DM1 – Esai (C3)
dm1_scores = pd.DataFrame({
    "ID"                  : ids,
    "C3_Kesesuaian_Tema"  : np.round(np.random.uniform(5, 10, n_sub), 2),
    "C3_Kejelasan_Tujuan" : np.round(np.random.uniform(5, 10, n_sub), 2),
    "C3_Orisinalitas"     : np.round(np.random.uniform(4, 10, n_sub), 2),
    "C3_Dampak_Kontribusi": np.round(np.random.uniform(5, 10, n_sub), 2),
})

# Skor DM2 – Rencana Studi (C6)
dm2_scores = pd.DataFrame({
    "ID"                  : ids,
    "C6_Alasan_Prodi"     : np.round(np.random.uniform(5, 10, n_sub), 2),
    "C6_Topik_Tesis"      : np.round(np.random.uniform(4, 10, n_sub), 2),
    "C6_Rencana_Semester" : np.round(np.random.uniform(5, 10, n_sub), 2),
})

# Skor DM3 – Wawancara (C7)
dm3_scores = pd.DataFrame({
    "ID"                  : ids,
    "C7_Kesesuaian_Esai"  : np.round(np.random.uniform(5, 10, n_sub), 2),
    "C7_Komunikasi"       : np.round(np.random.uniform(5, 10, n_sub), 2),
    "C7_Motivasi"         : np.round(np.random.uniform(5, 10, n_sub), 2),
    "C7_Critical_Thinking": np.round(np.random.uniform(4, 10, n_sub), 2),
    "C7_Prestasi"         : np.round(np.random.uniform(3, 10, n_sub), 2),
})

# ─── FUNGSI TOPSIS ──────────────────────────────────────────
def topsis(matrix, weights, benefit_flags):
    """
    matrix       : np.ndarray (n_alternatif x n_kriteria)
    weights      : list/array bobot (jumlah = 1)
    benefit_flags: list bool (True=benefit, False=cost)
    Return: array skor preferensi (semakin besar semakin baik)
    """
    # Normalisasi
    norm = matrix / np.sqrt((matrix ** 2).sum(axis=0))
    # Bobot
    weighted = norm * np.array(weights)
    # Solusi ideal positif & negatif
    ideal_pos = np.where(benefit_flags, weighted.max(axis=0), weighted.min(axis=0))
    ideal_neg = np.where(benefit_flags, weighted.min(axis=0), weighted.max(axis=0))
    # Jarak
    d_pos = np.sqrt(((weighted - ideal_pos) ** 2).sum(axis=1))
    d_neg = np.sqrt(((weighted - ideal_neg) ** 2).sum(axis=1))
    # Skor preferensi
    score = d_neg / (d_pos + d_neg)
    return score

# ─── TOPSIS PER DM ──────────────────────────────────────────

# DM1 – Esai
c3_cols   = ["C3_Kesesuaian_Tema", "C3_Kejelasan_Tujuan", "C3_Orisinalitas", "C3_Dampak_Kontribusi"]
w_c3      = [0.30, 0.25, 0.25, 0.20]
m_c3      = dm1_scores[c3_cols].values
score_dm1 = topsis(m_c3, w_c3, [True]*4)

# DM2 – Rencana Studi
c6_cols   = ["C6_Alasan_Prodi", "C6_Topik_Tesis", "C6_Rencana_Semester"]
w_c6      = [0.35, 0.35, 0.30]
m_c6      = dm2_scores[c6_cols].values
score_dm2 = topsis(m_c6, w_c6, [True]*3)

# DM3 – Wawancara
c7_cols   = ["C7_Kesesuaian_Esai", "C7_Komunikasi", "C7_Motivasi", "C7_Critical_Thinking", "C7_Prestasi"]
w_c7      = [0.20, 0.20, 0.20, 0.20, 0.20]
m_c7      = dm3_scores[c7_cols].values
score_dm3 = topsis(m_c7, w_c7, [True]*5)

print(f"\n✅ TOPSIS selesai untuk {n_sub} pendaftar (3 DM)")

# ─── GDSS BORDA ─────────────────────────────────────────────
def borda_aggregation(scores_list, ids):
    """
    scores_list : list of np.array skor dari setiap DM
    ids         : list ID alternatif
    Return      : DataFrame dengan Borda Score dan ranking akhir
    """
    n = len(ids)
    rankings = []
    for sc in scores_list:
        rank = pd.Series(sc).rank(ascending=False, method="min").values.astype(int)
        borda_pts = n - rank   # poin borda = n - rank
        rankings.append(borda_pts)

    borda_total = np.sum(rankings, axis=0)
    df_borda = pd.DataFrame({
        "ID"            : ids,
        "Borda_DM1_Esai": rankings[0],
        "Borda_DM2_RS"  : rankings[1],
        "Borda_DM3_Waw" : rankings[2],
        "Borda_Total"   : borda_total,
    })
    df_borda["Ranking_GDSS"] = df_borda["Borda_Total"].rank(ascending=False, method="min").astype(int)
    df_borda = df_borda.sort_values("Ranking_GDSS").reset_index(drop=True)
    return df_borda

df_borda = borda_aggregation([score_dm1, score_dm2, score_dm3], ids)

# Tambahkan skor TOPSIS per DM
df_borda["TOPSIS_DM1"] = np.round(score_dm1[df_borda.index], 4)
df_borda["TOPSIS_DM2"] = np.round(score_dm2[df_borda.index], 4)
df_borda["TOPSIS_DM3"] = np.round(score_dm3[df_borda.index], 4)

# Gabungkan dengan nama
id_to_name = dict(zip(ids, names_sub))
df_borda["Nama"] = df_borda["ID"].map(id_to_name)

print(f"\n✅ GDSS Borda selesai – Ranking GDSS ditetapkan")

print(f"\n{'='*65}")
print("  HASIL RANKING GDSS (TOP 20):")
print(f"{'='*65}")
top20 = df_borda.head(20)[["Ranking_GDSS", "ID", "Nama",
                             "TOPSIS_DM1", "TOPSIS_DM2", "TOPSIS_DM3",
                             "Borda_Total"]]
print(tabulate(top20, headers="keys", tablefmt="grid",
               showindex=False, floatfmt=".4f"))

# ─── VISUALISASI SUBSTANSI ──────────────────────────────────
fig, axes = plt.subplots(1, 3, figsize=(18, 5))
fig.suptitle("TAHAP SUBSTANSI – Distribusi Skor TOPSIS per DM", fontsize=13, fontweight="bold")

dm_info = [
    (score_dm1, "DM1 – Penilai Esai (C3)", "#3498db"),
    (score_dm2, "DM2 – Penilai Rencana Studi (C6)", "#2ecc71"),
    (score_dm3, "DM3 – Penilai Wawancara (C7)", "#e67e22"),
]
for ax, (sc, title, color) in zip(axes, dm_info):
    ax.hist(sc, bins=20, color=color, edgecolor="white", alpha=0.85)
    ax.set_title(title, fontsize=10)
    ax.set_xlabel("Skor TOPSIS")
    ax.set_ylabel("Jumlah Pendaftar")
    ax.axvline(sc.mean(), color="red", linestyle="--", label=f"Rata-rata: {sc.mean():.3f}")
    ax.legend(fontsize=8)

plt.tight_layout()
plt.savefig("substansi_topsis.png", dpi=120, bbox_inches="tight")
plt.show()
print("📈 Grafik substansi tersimpan: substansi_topsis.png")

# Top 20 Borda visualisasi
fig, ax = plt.subplots(figsize=(14, 8))
top_plot = df_borda.head(20).copy()
top_plot["Label"] = top_plot["Ranking_GDSS"].astype(str) + ". " + top_plot["Nama"]

x = np.arange(len(top_plot))
w = 0.25
bars1 = ax.bar(x - w,   top_plot["Borda_DM1_Esai"], w, label="Borda DM1 (Esai)", color="#3498db")
bars2 = ax.bar(x,       top_plot["Borda_DM2_RS"],   w, label="Borda DM2 (Rencana Studi)", color="#2ecc71")
bars3 = ax.bar(x + w,   top_plot["Borda_DM3_Waw"],  w, label="Borda DM3 (Wawancara)", color="#e67e22")

ax.set_xticks(x)
ax.set_xticklabels(top_plot["Label"], rotation=45, ha="right", fontsize=8)
ax.set_ylabel("Poin Borda")
ax.set_title("TOP 20 – Skor Borda per Decision Maker", fontsize=12, fontweight="bold")
ax.legend()
plt.tight_layout()
plt.savefig("borda_top20.png", dpi=120, bbox_inches="tight")
plt.show()
print("📈 Grafik Borda Top 20 tersimpan: borda_top20.png")

# ─── BAGIAN 4: TAHAP PENETAPAN ──────────────────────────────
print("\n" + "=" * 65)
print("  TAHAP 3: PENETAPAN – KEPALA PUSLAPDIK")
print("=" * 65)

KUOTA_BEASISWA = 30  # kuota penerima

df_penetapan = df_borda.head(KUOTA_BEASISWA).copy()
df_penetapan["Status_Penetapan"] = "DITETAPKAN"
df_penetapan["Catatan_Kepala"]   = "Setuju – sesuai ranking GDSS"

# Simulasi: Kepala Puslapdik override 2 kandidat
OVERRIDE_IDX = [3, 7]   # index (0-based) yang di-override
ALASAN_OVERRIDE = {
    3: "Conflict of interest – tidak dapat ditetapkan",
    7: "Dokumen pendukung tambahan diperlukan – ditunda",
}

for idx, alasan in ALASAN_OVERRIDE.items():
    df_penetapan.loc[idx, "Status_Penetapan"] = "OVERRIDE_DITOLAK"
    df_penetapan.loc[idx, "Catatan_Kepala"]   = f"Tidak Setuju – {alasan}"

# Kandidat pengganti dari ranking berikutnya
df_pengganti = df_borda.iloc[KUOTA_BEASISWA:KUOTA_BEASISWA + len(OVERRIDE_IDX)].copy()
df_pengganti["Status_Penetapan"] = "DITETAPKAN (Pengganti)"
df_pengganti["Catatan_Kepala"]   = "Masuk sebagai pengganti dari override"

df_final = pd.concat([df_penetapan, df_pengganti], ignore_index=True)
df_final  = df_final.sort_values(["Status_Penetapan", "Ranking_GDSS"]).reset_index(drop=True)

# Tampilkan hasil penetapan
print(f"\n📋 KEPUTUSAN KEPALA PUSLAPDIK (KUOTA: {KUOTA_BEASISWA} penerima)")
print(f"{'='*65}")

ditetapkan = df_final[df_final["Status_Penetapan"].str.startswith("DITETAPKAN")]
override   = df_final[df_final["Status_Penetapan"] == "OVERRIDE_DITOLAK"]

print(f"\n✅ PENERIMA BEASISWA DITETAPKAN ({len(ditetapkan)} orang):")
cols_out = ["Ranking_GDSS", "ID", "Nama", "Borda_Total", "Status_Penetapan", "Catatan_Kepala"]
print(tabulate(ditetapkan[cols_out].head(10), headers="keys",
               tablefmt="grid", showindex=False))
print(f"  ... dan {max(0, len(ditetapkan)-10)} penerima lainnya")

print(f"\n🔄 KANDIDAT DI-OVERRIDE ({len(override)} orang):")
print(tabulate(override[cols_out], headers="keys", tablefmt="grid", showindex=False))

# ─── VISUALISASI PENETAPAN ──────────────────────────────────
fig, axes = plt.subplots(1, 2, figsize=(14, 5))
fig.suptitle("TAHAP PENETAPAN – Rekapitulasi Akhir", fontsize=13, fontweight="bold")

status_final = df_final["Status_Penetapan"].value_counts()
colors_final = {"DITETAPKAN": "#2ecc71",
                "DITETAPKAN (Pengganti)": "#3498db",
                "OVERRIDE_DITOLAK": "#e74c3c"}
pie_colors = [colors_final.get(s, "#95a5a6") for s in status_final.index]
axes[0].pie(status_final, labels=status_final.index, autopct="%1.0f%%",
            colors=pie_colors, startangle=90)
axes[0].set_title("Komposisi Keputusan Penetapan")

# Heatmap skor TOPSIS top 15
top15 = df_borda.head(15).set_index("Nama")[["TOPSIS_DM1", "TOPSIS_DM2", "TOPSIS_DM3"]]
top15.columns = ["DM1\n(Esai)", "DM2\n(Rencana Studi)", "DM3\n(Wawancara)"]
sns.heatmap(top15, annot=True, fmt=".3f", cmap="YlGn", ax=axes[1],
            linewidths=0.5, cbar_kws={"shrink": 0.8})
axes[1].set_title("Heatmap Skor TOPSIS Top 15 Penerima")
axes[1].set_ylabel("")

plt.tight_layout()
plt.savefig("penetapan_final.png", dpi=120, bbox_inches="tight")
plt.show()
print("📈 Grafik penetapan tersimpan: penetapan_final.png")

# ─── RINGKASAN AKHIR ─────────────────────────────────────────
print("\n" + "=" * 65)
print("  RINGKASAN AKHIR SISTEM GDSS BEASISWA UNGGULAN")
print("=" * 65)
print(f"""
  📌 Total Pendaftar                   : {N}
  📋 Lulus Administrasi                : {len(df_lulus_admin)}
  ⛔ Gugur Administrasi                : {N - len(df_lulus_admin)}

  📊 Masuk Tahap Substansi (TOPSIS)    : {n_sub}
     • TOPSIS DM1 (Esai / C3)          : selesai
     • TOPSIS DM2 (Rencana Studi / C6) : selesai
     • TOPSIS DM3 (Wawancara / C7)     : selesai
     • Agregasi GDSS (Borda)           : selesai

  🎓 Kuota Beasiswa                    : {KUOTA_BEASISWA}
  ✅ Ditetapkan oleh Kepala Puslapdik  : {len(ditetapkan)}
  🔄 Di-override                        : {len(override)}

  File output:
     • administrasi_summary.png
     • substansi_topsis.png
     • borda_top20.png
     • penetapan_final.png
""")

# ─── EXPORT HASIL KE CSV ─────────────────────────────────────
df_admin.to_csv("hasil_administrasi.csv", index=False)
df_borda.to_csv("hasil_substansi_borda.csv", index=False)
df_final.to_csv("hasil_penetapan_final.csv", index=False)

print("  💾 Data tersimpan ke CSV:")
print("     • hasil_administrasi.csv")
print("     • hasil_substansi_borda.csv")
print("     • hasil_penetapan_final.csv")
print("\n" + "=" * 65)
print("  ✅ SISTEM BERHASIL DIJALANKAN")
print("=" * 65)